GRANT EXECUTE ON FUNCTION current_user_id() TO PUBLIC;
GRANT EXECUTE ON FUNCTION is_system_admin() TO PUBLIC;
GRANT EXECUTE ON FUNCTION has_active_membership(UUID, UUID) TO PUBLIC;
GRANT EXECUTE ON FUNCTION has_active_admin_membership(UUID, UUID) TO PUBLIC;
