REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM omnira_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM omnira_app;
REVOKE USAGE ON SCHEMA public FROM omnira_app;
REVOKE CONNECT ON DATABASE omnira_dev FROM omnira_app;
DROP ROLE IF EXISTS omnira_app;
