-- Rollback ADR-0026/0030: Hub RLS policies

DROP POLICY IF EXISTS service_hubs_read ON service_hubs;
DROP POLICY IF EXISTS service_hubs_insert ON service_hubs;
DROP POLICY IF EXISTS service_hubs_update ON service_hubs;
DROP POLICY IF EXISTS service_hubs_delete ON service_hubs;
DROP POLICY IF EXISTS hub_memberships_read ON hub_memberships;
DROP POLICY IF EXISTS hub_memberships_insert ON hub_memberships;
DROP POLICY IF EXISTS hub_memberships_update ON hub_memberships;
DROP POLICY IF EXISTS hub_memberships_delete ON hub_memberships;
DROP POLICY IF EXISTS hub_contracts_read ON hub_tenant_service_contracts;
DROP POLICY IF EXISTS hub_contracts_insert ON hub_tenant_service_contracts;
DROP POLICY IF EXISTS hub_contracts_update ON hub_tenant_service_contracts;
DROP POLICY IF EXISTS hub_contracts_delete ON hub_tenant_service_contracts;
DROP POLICY IF EXISTS effective_grants_read ON effective_access_grants;
DROP POLICY IF EXISTS effective_grants_insert ON effective_access_grants;
DROP POLICY IF EXISTS effective_grants_update ON effective_access_grants;
DROP POLICY IF EXISTS effective_grants_delete ON effective_access_grants;
DROP POLICY IF EXISTS work_pools_read ON work_pools;
DROP POLICY IF EXISTS work_pools_insert ON work_pools;
DROP POLICY IF EXISTS work_pools_update ON work_pools;
DROP POLICY IF EXISTS work_pools_delete ON work_pools;
DROP POLICY IF EXISTS skills_read ON skills;
DROP POLICY IF EXISTS skills_insert ON skills;
DROP POLICY IF EXISTS skills_update ON skills;
DROP POLICY IF EXISTS skills_delete ON skills;
DROP POLICY IF EXISTS work_pool_members_read ON work_pool_members;
DROP POLICY IF EXISTS work_pool_members_insert ON work_pool_members;
DROP POLICY IF EXISTS work_pool_members_update ON work_pool_members;
DROP POLICY IF EXISTS work_pool_members_delete ON work_pool_members;
DROP POLICY IF EXISTS agent_skills_read ON agent_skills;
DROP POLICY IF EXISTS agent_skills_insert ON agent_skills;
DROP POLICY IF EXISTS agent_skills_update ON agent_skills;
DROP POLICY IF EXISTS agent_skills_delete ON agent_skills;
DROP POLICY IF EXISTS hub_inbox_read ON hub_inbox_items;
DROP POLICY IF EXISTS hub_inbox_insert ON hub_inbox_items;
DROP POLICY IF EXISTS hub_inbox_update ON hub_inbox_items;
DROP POLICY IF EXISTS hub_inbox_delete ON hub_inbox_items;

ALTER TABLE service_hubs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE service_hubs DISABLE ROW LEVEL SECURITY;
ALTER TABLE hub_memberships NO FORCE ROW LEVEL SECURITY;
ALTER TABLE hub_memberships DISABLE ROW LEVEL SECURITY;
ALTER TABLE hub_tenant_service_contracts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE hub_tenant_service_contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_pools NO FORCE ROW LEVEL SECURITY;
ALTER TABLE work_pools DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_pool_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE work_pool_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE skills NO FORCE ROW LEVEL SECURITY;
ALTER TABLE skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE agent_skills NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE effective_access_grants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE effective_access_grants DISABLE ROW LEVEL SECURITY;
ALTER TABLE hub_inbox_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE hub_inbox_items DISABLE ROW LEVEL SECURITY;

DROP FUNCTION IF EXISTS has_active_grant_on_contract(UUID, UUID);
DROP FUNCTION IF EXISTS has_active_hub_access(UUID, UUID, UUID, UUID, BOOLEAN, BOOLEAN);
DROP FUNCTION IF EXISTS is_hub_admin(UUID, UUID);
DROP FUNCTION IF EXISTS is_hub_member(UUID, UUID);
