package waha

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/omnira/omnira/internal/channels/ports"

	"github.com/omnira/omnira/internal/channels/domain"
)

var (
	ErrAuthentication        = ports.ErrAuthentication
	ErrConfiguration         = ports.ErrConfiguration
	ErrTransient             = ports.ErrTransient
	ErrPermanent             = ports.ErrPermanent
	ErrRateLimited           = ports.ErrRateLimited
	ErrProviderUnavailable   = ports.ErrProviderUnavailable
	ErrSessionDisconnected   = ports.ErrSessionDisconnected
	ErrUnknown               = ports.ErrUnknown
	ErrMediaSourceNotAllowed = ports.ErrMediaSourceNotAllowed
	ErrProviderIDMismatch    = ports.ErrProviderIDMismatch
)

const maxDownloadedMedia = 25 << 20

// Client is thin WAHA transport. It knows no Tenant, ChannelConnection or
// WAHA payload domain; adapter/application layers own those boundaries.
type Client struct {
	baseURL    string
	apiKey     string
	httpClient *http.Client
}

// Session is the provider response reduced to fields needed by U2. Raw WAHA
// payloads must not cross adapter boundary.
type Session struct {
	Name   string `json:"name"`
	Status string `json:"status"`
	Engine struct {
		Name string `json:"engine"`
	} `json:"engine"`
}

type QRCode struct {
	MIMEType string `json:"mimetype"`
	Data     string `json:"data"`
}

type Account struct {
	ID       string `json:"id"`
	PushName string `json:"pushName"`
}

type sendTextRequest struct {
	Session string `json:"session"`
	ChatID  string `json:"chatId"`
	Text    string `json:"text"`
	// ID is the pre-generated, stable WAHA/GOWS message id (see
	// GET /api/{session}/new-message-id). Forwarded verbatim to the
	// underlying send, byte for byte — never generated by this client.
	// Runtime-proven (PILOT.4A0) to make a repeated send with the same id
	// deduplicate down to exactly one visible WhatsApp delivery on
	// WAHA/GOWS 2026.8.2. Omitted (empty) only for call sites that have not
	// yet adopted stable-id reservation.
	ID string `json:"id,omitempty"`
}

type sendTextResponse struct {
	ID string `json:"id"`
}

type newMessageIDResponse struct {
	ID string `json:"id"`
}

type WebhookConfig struct {
	URL    string   `json:"url"`
	Events []string `json:"events"`
	HMAC   struct {
		Key string `json:"key"`
	} `json:"hmac"`
}

type sessionCreateRequest struct {
	Name   string `json:"name"`
	Start  bool   `json:"start"`
	Config struct {
		Webhooks []WebhookConfig `json:"webhooks,omitempty"`
	} `json:"config,omitempty"`
}

func NewClient(baseURL, apiKey string, httpClient *http.Client) (*Client, error) {
	u, err := url.Parse(strings.TrimRight(baseURL, "/"))
	if err != nil || u.Scheme != "http" && u.Scheme != "https" || u.Host == "" {
		return nil, ErrConfiguration
	}
	if apiKey == "" {
		return nil, ErrConfiguration
	}
	if httpClient == nil {
		httpClient = &http.Client{Timeout: 15 * time.Second, CheckRedirect: noRedirect}
	}
	if httpClient.CheckRedirect == nil {
		hc := *httpClient // never mutate the caller's client
		hc.CheckRedirect = noRedirect
		httpClient = &hc
	}
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), apiKey: apiKey, httpClient: httpClient}, nil
}

func (c *Client) Health(ctx context.Context) error {
	_, err := c.do(ctx, http.MethodGet, "/health", nil, nil)
	return err
}

func (c *Client) CreateSession(ctx context.Context, name string) (Session, error) {
	return c.createSession(ctx, sessionCreateRequest{Name: name, Start: false})
}

func (c *Client) CreateSessionWithWebhook(ctx context.Context, name, webhookURL, hmacKey string) (Session, error) {
	request := sessionCreateRequest{Name: name, Start: false}
	webhook := WebhookConfig{URL: webhookURL, Events: []string{"message.any", "message.ack", "session.status"}}
	webhook.HMAC.Key = hmacKey
	request.Config.Webhooks = []WebhookConfig{webhook}
	return c.createSession(ctx, request)
}

func (c *Client) createSession(ctx context.Context, request sessionCreateRequest) (Session, error) {
	bodyBytes, err := json.Marshal(request)
	if err != nil {
		return Session{}, ErrConfiguration
	}
	body := strings.NewReader(string(bodyBytes))
	var session Session
	_, err = c.do(ctx, http.MethodPost, "/api/sessions", body, &session)
	return session, err
}

func (c *Client) GetSession(ctx context.Context, name string) (Session, error) {
	var session Session
	_, err := c.do(ctx, http.MethodGet, "/api/sessions/"+url.PathEscape(name), nil, &session)
	return session, err
}

func (c *Client) StartSession(ctx context.Context, name string) (Session, error) {
	return c.sessionAction(ctx, name, "start")
}

func (c *Client) StopSession(ctx context.Context, name string) (Session, error) {
	return c.sessionAction(ctx, name, "stop")
}

func (c *Client) RestartSession(ctx context.Context, name string) (Session, error) {
	return c.sessionAction(ctx, name, "restart")
}

func (c *Client) GetQRCode(ctx context.Context, name string) (QRCode, error) {
	var qr QRCode
	_, err := c.doWithHeaders(ctx, http.MethodGet, "/api/"+url.PathEscape(name)+"/auth/qr", nil,
		map[string]string{"Accept": "application/json"}, &qr)
	return qr, err
}

func (c *Client) GetMe(ctx context.Context, name string) (*Account, error) {
	var account *Account
	_, err := c.do(ctx, http.MethodGet, "/api/sessions/"+url.PathEscape(name)+"/me", nil, &account)
	return account, err
}

// SendText calls WAHA's provider-neutral endpoint. The application/outbox
// owns idempotency because WAHA has no stable idempotency-key contract.
// SendText posts a text message. messageID is the stable, pre-reserved WAHA
// message id (from NewMessageID) that must be forwarded verbatim — the
// caller, never this client, decides that value and is responsible for its
// durability across retries.
func (c *Client) SendText(ctx context.Context, name, chatID, text, messageID string) (string, error) {
	body, err := json.Marshal(sendTextRequest{Session: name, ChatID: chatID, Text: text, ID: messageID})
	if err != nil {
		return "", ErrConfiguration
	}
	var response sendTextResponse
	if _, err = c.do(ctx, http.MethodPost, "/api/sendText", strings.NewReader(string(body)), &response); err != nil {
		return "", err
	}
	if response.ID == "" {
		return "", fmt.Errorf("%w: sendText response missing message id", ErrUnknown)
	}
	return response.ID, nil
}

type mediaFile struct {
	Mimetype string `json:"mimetype"`
	Filename string `json:"filename,omitempty"`
	Data     string `json:"data"`
}

type sendMediaRequest struct {
	Session string    `json:"session"`
	ChatID  string    `json:"chatId"`
	File    mediaFile `json:"file"`
	Caption string    `json:"caption,omitempty"`
}

// noRedirect: WAHA never legitimately redirects an API call, and a redirect would carry the API key (a custom header, which net/http does
// not strip) and a file to another host.
func noRedirect(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }

// mediaSlots bounds the media bodies built at once (base64 + JSON triple a file's size in memory).
var mediaSlots = make(chan struct{}, 2)

// mediaTimeout: a base64 body of up to ~22 MB needs longer than a text send.
const mediaTimeout = 90 * time.Second

// SendMedia posts a file through WAHA's image/video/voice/file endpoints. Unlike SendText there is no reserved id to make a repeat safe, so
// the CALLER (the provider) must treat any ambiguous failure as an unknown outcome and never retry it automatically.
func (c *Client) SendMedia(ctx context.Context, name, chatID, endpoint, mimetype, filename string, data []byte, caption string) (string, error) {
	switch endpoint {
	case "sendImage", "sendVideo", "sendVoice", "sendFile":
	default:
		return "", fmt.Errorf("%w: unsupported media endpoint", ErrPermanent)
	}
	ctx, cancel := context.WithTimeout(ctx, mediaTimeout)
	defer cancel()
	select {
	case mediaSlots <- struct{}{}:
		defer func() { <-mediaSlots }()
	case <-ctx.Done():
		return "", fmt.Errorf("%w: %w: waiting for a media slot", ErrProviderUnavailable, ErrTransient)
	}
	req := sendMediaRequest{Session: name, ChatID: chatID, Caption: caption,
		File: mediaFile{Mimetype: mimetype, Filename: filename, Data: base64.StdEncoding.EncodeToString(data)}}
	if endpoint == "sendVoice" {
		req.Caption = "" // voice notes carry no caption
	}
	body, err := json.Marshal(req)
	if err != nil {
		return "", ErrConfiguration
	}
	long := *c
	hc := *c.httpClient
	hc.Timeout = mediaTimeout
	hc.CheckRedirect = noRedirect
	long.httpClient = &hc
	var response sendTextResponse
	if _, err = long.do(ctx, http.MethodPost, "/api/"+endpoint, bytes.NewReader(body), &response); err != nil {
		return "", err
	}
	if response.ID == "" {
		return "", fmt.Errorf("%w: %s response missing message id", ErrUnknown, endpoint)
	}
	return response.ID, nil
}

// NewMessageID reserves a fresh, provider-generated stable message id with no
// delivery side effect (WAHA's own documented contract for this endpoint).
// It never sends a WhatsApp message.
func (c *Client) NewMessageID(ctx context.Context, name string) (string, error) {
	var response newMessageIDResponse
	if _, err := c.do(ctx, http.MethodGet, "/api/"+url.PathEscape(name)+"/new-message-id", nil, &response); err != nil {
		return "", err
	}
	if response.ID == "" {
		return "", fmt.Errorf("%w: new-message-id response missing id", ErrUnknown)
	}
	return response.ID, nil
}

func (c *Client) DownloadMedia(ctx context.Context, mediaURL string) ([]byte, string, error) {
	target, err := url.Parse(mediaURL)
	base, baseErr := url.Parse(c.baseURL)
	if err != nil || baseErr != nil || target.Scheme != base.Scheme || !strings.EqualFold(target.Host, base.Host) {
		return nil, "", ports.ErrMediaSourceNotAllowed
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, target.String(), nil)
	if err != nil {
		return nil, "", fmt.Errorf("%w: media request", ErrConfiguration)
	}
	req.Header.Set("X-Api-Key", c.apiKey)
	res, err := c.httpClient.Do(req)
	if err != nil {
		return nil, "", fmt.Errorf("%w: %w: %v", ErrProviderUnavailable, ErrTransient, err)
	}
	defer res.Body.Close()
	if res.StatusCode == http.StatusUnauthorized || res.StatusCode == http.StatusForbidden {
		return nil, "", ErrAuthentication
	}
	if res.StatusCode == http.StatusTooManyRequests {
		return nil, "", fmt.Errorf("%w: %w", ErrRateLimited, ErrTransient)
	}
	if res.StatusCode >= 500 {
		return nil, "", fmt.Errorf("%w: %w", ErrProviderUnavailable, ErrTransient)
	}
	if res.StatusCode >= 400 {
		return nil, "", ErrPermanent
	}
	data, err := io.ReadAll(io.LimitReader(res.Body, maxDownloadedMedia+1))
	if err != nil {
		return nil, "", fmt.Errorf("%w: media read", ErrUnknown)
	}
	if len(data) > maxDownloadedMedia {
		return nil, "", fmt.Errorf("%w: media exceeds size limit", ErrPermanent)
	}
	return data, res.Header.Get("Content-Type"), nil
}

func (c *Client) sessionAction(ctx context.Context, name, action string) (Session, error) {
	var session Session
	_, err := c.do(ctx, http.MethodPost, "/api/sessions/"+url.PathEscape(name)+"/"+action, nil, &session)
	return session, err
}

func (c *Client) do(ctx context.Context, method, path string, body io.Reader, result any) (int, error) {
	return c.doWithHeaders(ctx, method, path, body, nil, result)
}

func (c *Client) doWithHeaders(ctx context.Context, method, path string, body io.Reader, headers map[string]string, result any) (int, error) {
	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, body)
	if err != nil {
		return 0, ErrConfiguration
	}
	req.Header.Set("X-Api-Key", c.apiKey)
	for key, value := range headers {
		req.Header.Set(key, value)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	res, err := c.httpClient.Do(req)
	if err != nil {
		return 0, fmt.Errorf("%w: %w: %v", ErrProviderUnavailable, ErrTransient, err)
	}
	defer res.Body.Close()
	if res.StatusCode == http.StatusUnauthorized || res.StatusCode == http.StatusForbidden {
		return res.StatusCode, ErrAuthentication
	}
	if res.StatusCode == http.StatusTooManyRequests {
		return res.StatusCode, fmt.Errorf("%w: %w", ErrRateLimited, ErrTransient)
	}
	if res.StatusCode == http.StatusConflict {
		return res.StatusCode, fmt.Errorf("%w: %w", ErrSessionDisconnected, ErrPermanent)
	}
	if res.StatusCode >= 500 {
		return res.StatusCode, fmt.Errorf("%w: %w", ErrProviderUnavailable, ErrTransient)
	}
	if res.StatusCode >= 400 {
		return res.StatusCode, ErrPermanent
	}
	if result != nil {
		if err := json.NewDecoder(res.Body).Decode(result); err != nil {
			return res.StatusCode, fmt.Errorf("%w: decode response", ErrUnknown)
		}
	}
	return res.StatusCode, nil
}

type groupListItem struct {
	JID              string `json:"JID"`
	Name             string `json:"Name"`
	ParticipantCount int    `json:"ParticipantCount"`
}

// ListGroups returns the groups of a session (GOWS engine shape: JID, Name, ParticipantCount).
// The raw answer also carries every participant, so only the three fields needed are kept.
func (c *Client) ListGroups(ctx context.Context, name string) ([]domain.ProviderGroup, error) {
	var raw []groupListItem
	if _, err := c.do(ctx, http.MethodGet, "/api/"+url.PathEscape(name)+"/groups", nil, &raw); err != nil {
		return nil, err
	}
	out := make([]domain.ProviderGroup, 0, len(raw))
	for _, g := range raw {
		out = append(out, domain.ProviderGroup{JID: g.JID, Name: g.Name, ParticipantCount: g.ParticipantCount})
	}
	return out, nil
}
