/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--color-canvas)',
        surface: 'var(--color-surface)',
        'surface-muted': 'var(--color-surface-muted)',
        'surface-tertiary': 'var(--color-surface-tertiary)',
        'surface-hover': 'var(--color-surface-hover)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-light': 'var(--color-border-light)',
        'border-strong': 'var(--color-border-strong)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'accent-primary': 'var(--color-accent-primary)',
        'accent-primary-soft': 'var(--color-accent-primary-soft)',
        'accent-primary-hover': 'var(--color-accent-primary-hover)',
        'status-success': 'var(--color-status-success)',
        'status-success-soft': 'var(--color-status-success-soft)',
        'status-success-border': 'var(--color-status-success-border)',
        'status-success-hover': 'var(--color-status-success-hover)',
        'status-warning': 'var(--color-status-warning)',
        'status-warning-soft': 'var(--color-status-warning-soft)',
        'status-warning-border': 'var(--color-status-warning-border)',
        'status-warning-strong': 'var(--color-status-warning-strong)',
        'status-danger': 'var(--color-status-danger)',
        'status-danger-soft': 'var(--color-status-danger-soft)',
        'status-danger-border': 'var(--color-status-danger-border)',
        'status-danger-hover': 'var(--color-status-danger-hover)',
        'status-info': 'var(--color-status-info)',
        'status-info-soft': 'var(--color-status-info-soft)',
        'status-info-border': 'var(--color-status-info-border)',
      },
      width: {
        sidebar: 'var(--sidebar-width-desktop)',
        'sidebar-compact': 'var(--sidebar-width-tablet)',
      },
      fontFamily: {
        sans: 'var(--font-family)',
      },
      fontSize: {
        'display-lg': ['var(--text-display-lg-size)', 'var(--text-display-lg-height)'],
        'display-md': ['var(--text-display-md-size)', 'var(--text-display-md-height)'],
        'section-lg': ['var(--text-section-lg-size)', 'var(--text-section-lg-height)'],
        'section-md': ['var(--text-section-md-size)', 'var(--text-section-md-height)'],
        'section-sm': ['var(--text-section-sm-size)', 'var(--text-section-sm-height)'],
        'body-lg': ['var(--text-body-lg-size)', 'var(--text-body-lg-height)'],
        'body-md': ['var(--text-body-md-size)', 'var(--text-body-md-height)'],
        'body-sm': ['var(--text-body-sm-size)', 'var(--text-body-sm-height)'],
        caption: ['var(--text-caption-size)', 'var(--text-caption-height)'],
        metadata: ['var(--text-metadata-size)', 'var(--text-metadata-height)'],
        control: ['var(--text-control-size)', 'var(--text-control-height)'],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
      },
      borderRadius: {
        control: 'var(--radius-control)',
        card: 'var(--radius-card)',
        sheet: 'var(--radius-sheet)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        base: 'var(--transition-base)',
      },
    },
  },
  plugins: [],
}
